# Selecciona la imagen base
FROM openjdk:17-jdk-slim
# Define el directorio de trabajo para el comando
WORKDIR /usr/src/app/
# Copia de la aplicación compilada
COPY InternalService/target/InternalService-0.0.1-SNAPSHOT.jar /usr/src/app/
# Indica el puerto que expone el contenedor
EXPOSE 8181
# Comando que se ejecuta al hacer docker run
CMD [ "java", "-jar", "InternalService-0.0.1-SNAPSHOT.jar" ]